import type { BlogPost } from "../schemas/blog.schema";

export const blogPostsData: BlogPost[] = [
  {
    id: "skyrmion-lattice-dynamics",
    slug: "numerical-modeling-chiral-skyrmion-lattices",
    title:
      "Numerical Modeling of Chiral Néel Skyrmion Lattices under Interfacial Dzyaloshinskii-Moriya Interaction",
    date: "2026-08-15",
    category: "Simulation",
    location: "Adam Mickiewicz University / GPU Cluster",
    description:
      "Large-scale micromagnetic GPU simulation of topological skyrmion textures in ultrathin ferromagnetic multilayers. Investigating the phase transition between stripe domains and isolated topological whirls driven by perpendicular magnetic anisotropy and interfacial DMI.",
    imageUrl: "/images/blog/skyrmion-lattice-sim.webp",
    imageAlt: "Hexagonal lattice of Néel-type magnetic skyrmions in ferromagnetic thin film",
    tags: ["Skyrmions", "Micromagnetics", "GPU Simulation", "Topology"],
    featured: true,
    technicalDetails: {
      instrument: "CUDA MuMax3 Cluster",
      simulationEngine: "MuMax3.10 / Boris",
      magneticField: "120 mT out-of-plane",
    },
  },
  {
    id: "rptu-brillouin-optics-setup",
    slug: "brillouin-light-scattering-excitation-rptu",
    title: "Brillouin Light Scattering & Microwave Spin-Wave Excitation Setup at RPTU",
    date: "2026-07-28",
    category: "Laboratory",
    location: "RPTU Kaiserslautern-Landau, Germany",
    description:
      "High-resolution wave-vector and frequency-resolved Brillouin light scattering (BLS) optical table coupled with cryogenic electromagnet. Commissioning the excitation line for the MSCA CNMA auto-oscillator experiments in collaboration with Prof. P. Pirro's group.",
    imageUrl: "/images/blog/rptu-laser-lab.webp",
    imageAlt: "Laser optical table with electromagnet and spectrometers for spin-wave probing",
    tags: ["Laboratory", "Brillouin Scattering", "MSCA CNMA", "RPTU"],
    featured: true,
    technicalDetails: {
      instrument: "Tandem Fabry-Pérot Interferometer (TFP-2)",
      magneticField: "0 to 1.2 Tesla",
      temperature: "4.2 K - 300 K",
    },
  },
  {
    id: "curvilinear-nanomembrane-microscopy",
    slug: "scanning-electron-micrograph-curved-nanomembranes",
    title: "Scanning Electron Micrograph of 3D Curvilinear Magnetic Nanomembranes",
    date: "2026-06-12",
    category: "Equipment",
    location: "Faculty of Physics, UAM Poznań",
    description:
      "High-magnification SEM imaging of non-Euclidean curved magnetic shells. Geometry-induced effective gauge fields and curvature-induced magnetic anisotropy dictate novel spin-wave steering pathways along geodesic contours.",
    imageUrl: "/images/blog/curved-membrane-sem.webp",
    imageAlt:
      "Scanning electron micrograph of curved magnetic membrane with spherical and cylindrical indentations",
    tags: ["Curvilinear Magnetism", "SEM", "Nanomembranes", "Topology"],
    featured: false,
    technicalDetails: {
      instrument: "Field Emission Scanning Electron Microscope (FE-SEM)",
      magnification: "50,000x",
      temperature: "Room Temp",
    },
  },
  {
    id: "neuromorphic-spinwave-chip",
    slug: "nanofabricated-auto-oscillator-neuromorphic-computing",
    title: "Nanofabricated Auto-Oscillator Chip for Neuromorphic Reservoir Computing",
    date: "2026-05-04",
    category: "Laboratory",
    location: "RPTU Kaiserslautern-Landau / MSCA CNMA",
    description:
      "Packaged spintronic reservoir computing prototype wire-bonded in a gold carrier. Utilizing nonlinear spin-wave interference patterns generated by spin-torque auto-oscillators for low-power benchmark vowel and speech classification.",
    imageUrl: "/images/blog/neuromorphic-spinwave-chip.webp",
    imageAlt: "Packaged spintronics chip in gold-plated carrier showing interference spin wave ripples",
    tags: ["Neuromorphic Computing", "Reservoir Computing", "Spin Waves", "Hardware"],
    featured: true,
    technicalDetails: {
      instrument: "Keysight 50 GHz Vector Network Analyzer",
      magneticField: "85 mT in-plane",
    },
  },
  {
    id: "fresnel-lens-spinwave-focusing",
    slug: "direct-observation-spin-wave-focusing-fresnel-lens",
    title: "Direct Observation of Spin-Wave Focusing by a Sub-Micron Fresnel Zone Plate",
    date: "2026-04-18",
    category: "Publication",
    location: "Max Planck Institute for Intelligent Systems & RPTU",
    description:
      "Direct X-ray and optical observation of spin-wave caustic beams focused through nanoscale concentric semicircular Fresnel zone plates in yttrium iron garnet (YIG) thin films. Achieved diffraction-limited sub-micron focal spot with 6.8x amplitude enhancement.",
    imageUrl: "/images/blog/fresnel-lens-focusing.webp",
    imageAlt: "Concentric Fresnel zone plate focusing coherent spin waves into a bright focal caustic point",
    tags: ["Magnon Optics", "Fresnel Lens", "YIG Thin Films", "Wave Focusing"],
    featured: true,
    technicalDetails: {
      instrument: "Scanning Transmission X-ray Microscopy (STXM) & BLS",
      magneticField: "40 mT in-plane",
      temperature: "300 K",
    },
  },
  {
    id: "fibonacci-magnon-quasicrystal",
    slug: "magnonic-fibonacci-quasicrystals-reprogrammable-bandgaps",
    title: "Magnonic Fibonacci Quasicrystals & Reprogrammable Forbidden Band Gaps",
    date: "2026-03-22",
    category: "Simulation",
    location: "Institute of Spintronics and Quantum Information, AMU",
    description:
      "Demonstration of self-similar fractal localization of spin-wave modes in one-dimensional Fibonacci quasicrystals. Micro-focused BLS reveals reprogrammable forbidden transmission gaps controlled via local magnetic domain wall state reconfiguration.",
    imageUrl: "/images/blog/fibonacci-quasicrystal-bls.webp",
    imageAlt: "1D Fibonacci quasicrystal magnetic stripes under green laser illumination of BLS spectrometer",
    tags: ["Quasicrystals", "Fibonacci Lattice", "BLS Spectroscopy", "Band Gaps"],
    featured: false,
    technicalDetails: {
      instrument: "Micro-focused BLS & GPU Mumax3 FDTD",
      magneticField: "65 mT transverse",
      temperature: "Room Temp",
    },
  },
  {
    id: "spinwave-collimation-metasurface",
    slug: "spin-wave-collimation-flat-metasurface",
    title: "Spin-Wave Collimation Using Planar Gradient Refractive Metasurfaces",
    date: "2026-02-10",
    category: "Theory",
    location: "National Academy of Sciences & AMU Poznań",
    description:
      "Analytical derivation and numerical proof of wave-front phase transformation in graded-index magnonic metasurfaces. Cylindrical expanding spin waves entering the patterned metamaterial slab emerge as a reflectionless, parallel collimated nanoscale beam.",
    imageUrl: "/images/blog/spinwave-collimation-metasurface.webp",
    imageAlt: "Gradient metasurface converting cylindrical spin wave front into parallel collimated beam",
    tags: ["Metasurfaces", "Wave Collimation", "Theory", "Magnonics"],
    featured: true,
    technicalDetails: {
      instrument: "Analytical Scattering Matrix & MuMax3",
      frequency: "14.5 GHz",
      wavelength: "120 nm",
    },
  },
];
